# syntax=docker/dockerfile:1

ARG ZBASE_IMAGE=ghcr.io/zetaoss/zbase:latest
FROM ${ZBASE_IMAGE}

# https://hub.docker.com/_/composer/tags
COPY --from=composer:2.10 /usr/bin/composer /usr/bin/composer

RUN set -eux; \
    cd /var/www/html; \
    mv composer.local.json-sample composer.local.json; \
    composer update --no-dev --no-scripts --optimize-autoloader
